### ISSUE TITLE
Error when using T1 map MIT module

### ISSUE THREAD

**Issue by jweigandwhittier** [nifm-gin/MP3_User_Modules_Repository#1]
A coworker and I are encountering the same MATLAB error when trying to use the T1 mapping MIT module on the same Perfusion FAIR data. The error is as follows

    Unrecognized function or variable 'InvTimeRaw'.

    Error in Module_T1map_MIT (line 355)

        echotime_used = InvTimeRaw(it_mode,:) + NumSlice * interSliceTime;

    Error in MP3_pipeline>MP3_pipeline_execute_button_Callback (line 2358)

        eval(Module.command);

    Error in gui_mainfcn (line 95)

        feval(varargin{:});

    Error in MP3_pipeline (line 42)

    gui_mainfcn(gui_State, varargin{:});

    Error imatlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MP3_pipeline('MP3_pipeline_execute_button_Callback',hObject,eventdata,guidata(hObject))

    Error while evaluating UIControl Callback.

I am unsure whether this is caused by user error or something inherent to the program. We are both new to MATLAB and GitHub, so I hope this is the appropriate place to get feedback on this issue.

**Comment by blemasso** [comment]
Hi

We updated the code according to your data.
There were 2 issues :
   1) You are using a FAIR_RARE sequence which was not included in the code. Therefore, it could not calculate the parameter « InvTimeRaw », required in the final calcul.
   2) Your data a single single slice. This use case was not tested before (we always use a multi-slice sequence).

It should work now for your data. You can download the new version using the « dev » branche of the project MP3_User_Modules_Repository
--> https://github.com/nifm-gin/MP3_User_Modules_Repository/blob/dev/Relaxometry/Module_T1map_MIT.m

After testing on your dataset, could you give me a feedback in order to close this issue?

We also would like our code to be more robust, therefore, we would like to try with a multi-slice FAIR_RARE. 
Do you have such data ? 


Best

**Comment by jweigandwhittier** [comment]
Thank you so much for your help, I've tested the updated module and it works well! I don't believe we currently have any multi-slice FAIR_RARE data, but we will definitely try to collect some in order to help update the project.

What sequences do you generally use/recommend for T1 inversion recovery?

Thanks again!

**Comment by blemasso** [comment]
ok perfect!
In our lab we are using a FAIR-EPI sequence

Have fun with MP3 :)
